Dmytro ivanyshyn
m96roman/ja-bootcamp-2021 pull request #4
Opened 2021-09-27 15:16 UTC by DmytrIvd

Я не сильно зрозумів 13 завдання

2021-09-27 15:21 UTC, m96roman commented
> Я не сильно зрозумів 13 завдання. 
Впринципі ок. Тільки розкоментуй код. Мож закоментувати лише виклики функцій.

2021-09-27 15:58 UTC, olehkrut reviewed
Overall - everything is fine, well-done, I've added only minor suggestions

2021-09-27 15:58 UTC, olehkrut commented on Bootcamp/HelperMethods/Extensions.cs
> +        public static string swap(this string var, int index1, int index2)
all method names should begin with a capital letter, Swap not swap.

2021-09-27 15:58 UTC, olehkrut commented on Bootcamp/HelperMethods/Reader.cs
> +    public static class Reader
code style suggestion: use NewLine between methods and before return statement

2021-09-27 15:58 UTC, olehkrut commented on Bootcamp/Homework Ivanyshyn/Program.cs
> +            //Console.WriteLine($"Long string {str} something on end");
nameof isn't used )

2021-09-27 15:58 UTC, olehkrut commented on Bootcamp/Homework Ivanyshyn/Program.cs
> +            //Dont clearly understood
you did it write, so it's ok, well done!

2021-09-27 15:58 UTC, olehkrut commented on Bootcamp/Homework Ivanyshyn/Program.cs
> +            //        Console.WriteLine(i);
you also might optimize it a bit, just do `i += 8` after the `Console.WriteLine`

2021-09-27 21:20 UTC, m96roman reviewed
Good job!

2021-09-28 08:42 UTC, DmytrIvd commented on Bootcamp/Homework Ivanyshyn/Program.cs
> +            }
Changed algorithm a little

2021-09-28 10:20 UTC, DmytrIvd commented on Bootcamp/Homework Ivanyshyn/Program.cs
> +            //        Console.WriteLine(i);
All issues fixed in last commit

2021-09-29 09:16 UTC, olehkrut requested changes
pls move your homework task to the appropriate folder: `Bootcamp/Lecture1/Homework/YourName/` in doing so you'll have to update the solution file by removing old project and adding the existing one from new location, let me know in case of any problems

2021-09-29 14:58 UTC, DmytrIvd commented
> pls move your homework task to the appropriate folder: `Bootcamp/Lecture1/Homework/YourName/` in doing so you'll have to update the solution file by removing old project and adding the existing one from new location, let me know in case of any problems

Fixed this issue

2021-09-29 15:41 UTC, olehkrut approved these changes

2021-09-29 17:15 UTC, merged